spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/post-service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalHongfjdkfjd

logging.level:
  org.hibernate.SQL: debug


