drop table if exists users CASCADE;
create table users
(
    id   bigint generated by default as identity,
    name varchar(30),
    login_id varchar(50),
    password  varchar(50),
    primary key (id)
);

drop table if exists board CASCADE;
create table board
(
    id   bigint generated by default as identity,
    title varchar(30),
    content varchar,
    modified_date  datetime,
    member_id bigint,
    primary key (id)
);